<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SpeciesSpeciesAFRICANGRAYA</name>
   <tag></tag>
   <elementGuidId>205bfdf1-dd1a-4888-9774-95a20de724c3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__wrap</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> SpeciesSpeciesAFRICANGRAYALLIGATORALPACCAAMAZONAMPHIBIANANTELOPEAPEBABOONBATBEARBEARDEDDRAGONBIRDBISONBOACONSTRICTORBOBCATBUFFALOBULLCAMELCATCHAMELEONCHEETAHCHICKENCHIMPANZEECHINCHILLACOCKATIELCOCKATOOCONURECOWCOYOTECROCODILECYNODEERDINGODOGDONKEYDOVEDUCKELEPHANTFERRETFLAMINGOFOALFOXFROGGECKOGERBILGIRAFFEGOATGOOSEGUINEAPIGHAMSTERHEDGEHOGHORSEIGUANAJACKALJAGUARKANGAROOKITTENLARGEMAMMALLEMURLEOPARDLIONLIZARDLLAMALOVEBIRDLYNXMACAWMINKMONITORMONKEYMOUSEMYNAHOPOSSUMOSTRICHOTHEROXPANTHERPARAKEETPARROTPIGPONYPRAIRIEDOGPRIMATEPUMAPUPPYPYTHONRABBITRACCOONRATREPTILERHESUSSALAMANDERSEALSEALIONSHEEPSKUNKSMALLMAMMALSNAKESQUIRRELSTEERTIGERTOADTORTOISETOUCANTURTLEWATERBUFFALOWOLFZEBRABreed </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialogContent_14&quot;)/div[@class=&quot;modal__body&quot;]/form[@class=&quot;main__form form-group ng-valid ng-valid-maxlength ng-valid-mindate ng-valid-maxdate ng-valid-filtered ng-valid-valid ng-valid-minlength ng-valid-required ng-dirty ng-valid-parse&quot;]/fieldset[@class=&quot;form__content&quot;]/div[@class=&quot;form__cols&quot;]/div[@class=&quot;form__wrap&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//md-dialog-content[@id='dialogContent_14']/div[2]/form/fieldset/div[2]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Abbreviated history'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//fieldset/div[2]/div</value>
   </webElementXpaths>
</WebElementEntity>
