<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon-assets_ng_ic_home_15</name>
   <tag></tag>
   <elementGuidId>b40bd81a-7d9c-4d6f-ba19-eb1d1a6a761c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-assets_ng_ic_home_15</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/nav[@class=&quot;navbar navbar-inverse header-abaxis&quot;]/div[@class=&quot;col-md-12 col-sm-12 col-xs-12 container container-abaxis&quot;]/div[@class=&quot;col-md-8 col-sm-8 col-xs-8&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[1]/a[1]/div[1]/i[@class=&quot;icon-assets_ng_ic_home_15&quot;]</value>
   </webElementProperties>
</WebElementEntity>
