<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_ion-settings</name>
   <tag></tag>
   <elementGuidId>151c77ad-e6cb-468f-aaf4-c736ddb85d61</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ion-settings</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/nav[@class=&quot;navbar navbar-inverse header-abaxis&quot;]/div[@class=&quot;col-md-12 col-sm-12 col-xs-12 container container-abaxis&quot;]/div[@class=&quot;col-md-8 col-sm-8 col-xs-8&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[6]/a[1]/div[1]/i[@class=&quot;ion-settings&quot;]</value>
   </webElementProperties>
</WebElementEntity>
